// <auto-generated />
using DVDRentalStoreWebApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DVDRentalStoreWebApp.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210504115334_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            modelBuilder.Entity("DVDRentalStoreWebApp.Models.Copy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Copies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Available = false,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            MovieId = 5
                        });
                });

            modelBuilder.Entity("DVDRentalStoreWebApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 12.0,
                            Title = "Anchorman",
                            Year = 2000
                        },
                        new
                        {
                            Id = 2,
                            Price = 7.0,
                            Title = "Anchorman 2",
                            Year = 2001
                        },
                        new
                        {
                            Id = 3,
                            Price = 22.0,
                            Title = "Terminator",
                            Year = 1993
                        },
                        new
                        {
                            Id = 4,
                            Price = 29.0,
                            Title = "Jurassic Park",
                            Year = 1999
                        },
                        new
                        {
                            Id = 5,
                            Price = 11.0,
                            Title = "The Lord of the Rings",
                            Year = 1997
                        });
                });

            modelBuilder.Entity("DVDRentalStoreWebApp.Models.Copy", b =>
                {
                    b.HasOne("DVDRentalStoreWebApp.Models.Movie", "Movie")
                        .WithMany("Copies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DVDRentalStoreWebApp.Models.Movie", b =>
                {
                    b.Navigation("Copies");
                });
#pragma warning restore 612, 618
        }
    }
}
